### ISSUE TITLE
IOTA public key missing in release assets

### ISSUE THREAD

**Issue by Andrewskiz** [iotaledger/trinity-wallet#2093]
I am trying to verify the Trinity application on Linux but the GPG key is missing from the release. I see the .asc file, but not the public key .gpg file. 

Additionally, the link "How to verify authenticity of your Trinity download" is broken on both the github releases page and on https://trinity.iota.org/

**Comment by rihardsgravis** [comment]
Links "How to verify authenticity of your Trinity download", that also include the  fixed in trinity.iota.org and latest release notes.

**Comment by Andrewskiz** [comment]
Maybe I'm missing something, but I am still not seeing the .gpg file (public key) in the assets section under releases or on the documentation page.
