### ISSUE TITLE
[Bug] [Ledger] [Linux] Can't get past "Choose Ledger account index"

### ISSUE THREAD

**Issue by 70001** [iotaledger/trinity-wallet#574]
### Bug description
When setting up the ledger nano s with trinity wallet, after choosing account index 0 and pressing on "next", nothing happens. 
The animation of the button keeps spinning, but i can't get past this step.

### Environment Specs
Running Debian, Linux 4.9.0-8 with KDE (gnome-keyring installed)

- Trinity version: v0.4.0

### Steps To Reproduce
1. Download Trinity Appimage
2. Download dependencies
3. Unlock Nano S + Open IOTA Application
4. Try setting it up

### Expected behaviour
Getting past that "Choose your Ledger account index" screen

### Actual behaviour
"Next"-button keeps its spinning animation, doesn't do anything further.

**Comment by t0rv1c** [comment]
Same issue here (with Ubuntu 18.04)

**Comment by marcodepolo** [comment]
Same issue for me on Ubuntu 16.04.04

**Comment by 70001** [comment]
I have fixed it. The problem was that non-root was not able to access USB devices.
Running Trinity as root was not possible, therefore couldn't find it out earlier.

To fix it:

Download this script from LedgerHQ's github (e.g. with wget):
https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh

Then make it executable and run it.

It should work then. 
If not, you may need to add your user to the **plugdev** group.


But an error message from trinity like "Could not connect to ledger" or something similar would be nice.

**Comment by t0rv1c** [comment]
Awesome! Will try. Thanks

-------- Original Message --------

**Comment by t0rv1c** [comment]
@rajivshah3  Sorry, I didn't really pay attention when I saw the reply for the fix and was just happy to see it "fixed" and closed, but it doesn't fix the problem #574. I already had the rules added to my system and was happily using my ledger with Ledger Live... So this does not solve the issue.

**Comment by rajivshah3** [comment]
@t0rv1c it looks like this was fixed in https://github.com/iotaledger/trinity-wallet/pull/570, which will be included in the next build. If the issue still persists with the upcoming version, we can reopen this
