### ISSUE TITLE
Language resets itself to English on Mobile

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#677]
### Bug description
Languange changes itself back to English from time to time.

### Environment Specs
Samsung Galaxy S9+ & S8
Android 8.0

- Trinity version: 
0.5.1 (28)

### Steps To Reproduce
1. Initialize trinity with choosen language (different than English)
2. Close Trinity completelly
3. Open Trinity again (there is a big possibility that language resetted itself to English)

### Expected behaviour
Trinity should always remember/save selected language.

## Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
This bug seems to reappear from time to time. Once we fix it, we should probably figure out a way to test it so that this doesn't come up again.

**Comment by UmbahaSpodPaha** [comment]
This is still not fixed properly. Also after setting up Trinity with Polish language for example, we still have "English" selected in options.

@rajivshah3

**Comment by rajivshah3** [comment]
Sorry we haven't fixed this yet. I'll make sure to get to this soon. I'll close this as a duplicate of #1133

**Comment by cvarley100** [comment]
Reopened as #1133 specifies three different problems, of which two are fixed in #1146.

**Comment by UmbahaSpodPaha** [comment]
Problem still exist on newest 1.0.0. Not sure what and how often something triggers it. I even deleted all "junk-clearing" apps from my phone to test this one.

**Comment by cvarley100** [comment]
Repro steps (possibly Android only):

> - Fresh install
> - Select PL and set everything up
> - String are in PL
> - Close the app
> - Open again and it's reset to Eng

**Comment by UmbahaSpodPaha** [comment]
@cvarley100 me and few other people from discord confirming that the bug still exist on newest 1.1.0.

Problem confirmed on Android but don't know about iOS.
